project:
  type: website

website:
  title: "alphasignal533"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - lux
    css: styles.css
    toc: true



